define([], function() {



    return {
        api: {
            SERVER_ERROR: 'SERVER_ERROR',

            LOAD_DEALER_CONFIGURATIONS_SUCCESS: 'LOAD_DEALER_CONFIGURATIONS_SUCCESS',
            LOAD_LOCATIONS_SUCCESS: 'LOAD_LOCATIONS_SUCCESS',
            SEARCH_TIRES_SUCCESS: 'SEARCH_TIRES_SUCCESS',
            LOAD_SEARCH_PARAMETERS_SUCCESS: 'LOAD_SEARCH_PARAMETERS_SUCCESS',

            GET_VEHICLE_YEARS_SUCCESS: 'GET_VEHICLE_YEARS_SUCCESS',
            GET_VEHICLE_MAKES_SUCCESS: 'GET_VEHICLE_MAKES_SUCCESS',
            GET_VEHICLE_MODELS_SUCCESS: 'GET_VEHICLE_MODELS_SUCCESS',
            GET_VEHICLE_TRIMS_SUCCESS: 'GET_VEHICLE_TRIMS_SUCCESS',
            GET_VEHICLE_TIRES_SUCCESS: 'GET_VEHICLE_TIRES_SUCCESS',          
        }
        

    }

});