define([], function() {

    return {
        // ----- API actions -----
        BEFORE_SEND:     'BEFORE_SEND',
        API_ERROR:       'API_ERROR',

        LOAD_DEALER_CONFIGURATIONS_SUCCESS: 'LOAD_DEALER_CONFIGURATIONS_SUCCESS',
        LOAD_LOCATIONS_SUCCESS:             'LOAD_LOCATIONS_SUCCESS',
        SEARCH_TIRES_SUCCESS:               'SEARCH_TIRES_SUCCESS',
        LOAD_SEARCH_PARAMETERS_SUCCESS:     'LOAD_SEARCH_PARAMETERS_SUCCESS',

        GET_VEHICLE_YEARS_SUCCESS:  'GET_VEHICLE_YEARS_SUCCESS',
        GET_VEHICLE_MAKES_SUCCESS:  'GET_VEHICLE_MAKES_SUCCESS',
        GET_VEHICLE_MODELS_SUCCESS: 'GET_VEHICLE_MODELS_SUCCESS',
        GET_VEHICLE_TRIMS_SUCCESS:  'GET_VEHICLE_TRIMS_SUCCESS',
        GET_VEHICLE_TIRES_SUCCESS:  'GET_VEHICLE_TIRES_SUCCESS',

        UPDATE_QUOTE_SUCCESS:   'UPDATE_QUOTE_SUCCESS',

        SEND_APPOINTMENT_SUCCESS:     'SEND_APPOINTMENT_SUCCESS',
        SEND_QUOTE_REQUEST_SUCCESS:   'SEND_QUOTE_REQUEST_SUCCESS',
        SEND_EMAIL_SUCCESS:           'SEND_EMAIL_SUCCESS',
        PRINT_QUOTE_SUCCESS:          'PRINT_QUOTE_SUCCESS',

        SEND_APPOINTMENT_ERROR:     'SEND_APPOINTMENT_ERROR',
        SEND_QUOTE_REQUEST_ERROR:   'SEND_QUOTE_REQUEST_ERROR',
        SEND_EMAIL_ERROR:           'SEND_EMAIL_ERROR',
        PRINT_QUOTE_ERROR:          'PRINT_QUOTE',

        PAYMENT_ORDER_SUCCESS:      'PAYMENT_ORDER_SUCCESS',


        // ----- View actions -----
        CHANGE_LOCATION:             'CHANGE_LOCATION',
        CHANGE_SEARCH_TIRE_PARAM:    'CHANGE_SEARCH_TIRE_PARAM',
        CHANGE_SEARCH_VEHICLE_PARAM: 'CHANGE_SEARCH_VEHICLE_PARAM',
        CHANGE_SEARCH_BY:            'CHANGE_SEARCH_BY',

        SEARCH_TIRES:                'SEARCH_TIRES',
                
        SELECT_TIRE:  'SELECT_TIRE',
        UPDATE_QUOTE: 'UPDATE_QUOTE',

        SHOW_QUOTE_REQUEST_FORM: 'SHOW_QUOTE_REQUEST_FORM',
        SHOW_APPOINTMENT_FORM:   'SHOW_APPOINTMENT_FORM',
        SHOW_QUOTE_PAGE:         'SHOW_QUOTE_PAGE',
        SHOW_QUOTE_EMAIL_FORM:   'SHOW_QUOTE_EMAIL_FORM',
        SHOW_QUOTE_PRINT_FORM:   'SHOW_QUOTE_PRINT_FORM',

        CREATE_ORDER:            'CREATE_ORDER',
        PAYMENT_ORDER:           'PAYMENT_ORDER',

        SEND_APPOINTMENT:   'SEND_APPOINTMENT',
        SEND_QUOTE_REQUEST: 'SEND_QUOTE_REQUEST',
        SEND_EMAIL:         'SEND_EMAIL',
        PRINT_QUOTE:        'PRINT_QUOTE',
    }

});