define([], function() {

    return {
        // ----- API events -----
        BEFORE_REQUEST:    'BEFORE_REQUEST',
        RESPONSE_RECEIVED: 'RESPONSE_RECEIVED',
        ERROR_RESPONSE:    'ERROR_RESPONSE',

        LOAD_DEALER_CONFIG_SUCCESS:         'LOAD_DEALER_CONFIG_SUCCESS',
        LOAD_DEALER_INFO_SUCCESS:           'LOAD_DEALER_INFO_SUCCESS',
        LOAD_LOCATIONS_SUCCESS:             'LOAD_LOCATIONS_SUCCESS',
        LOAD_LOCATION_CONFIG_SUCCESS:       'LOAD_LOCATION_CONFIG_SUCCESS',
        LOAD_TIRE_PARAMETERS_SUCCESS:       'LOAD_TIRE_PARAMETERS_SUCCESS',

        SEARCH_TIRES_SUCCESS:               'SEARCH_TIRES_SUCCESS',

        GET_VEHICLE_YEARS_SUCCESS:  'GET_VEHICLE_YEARS_SUCCESS',
        GET_VEHICLE_MAKES_SUCCESS:  'GET_VEHICLE_MAKES_SUCCESS',
        GET_VEHICLE_MODELS_SUCCESS: 'GET_VEHICLE_MODELS_SUCCESS',
        GET_VEHICLE_TRIMS_SUCCESS:  'GET_VEHICLE_TRIMS_SUCCESS',
        GET_VEHICLE_TIRES_SUCCESS:  'GET_VEHICLE_TIRES_SUCCESS',
        GET_VEHICLE_OPTIONS_SUCCESS: 'GET_VEHICLE_OPTIONS_SUCCESS',

        LOAD_QUOTE_SUCCESS:          'LOAD_QUOTE_SUCCESS',

        SEND_APPOINTMENT_SUCCESS:     'SEND_APPOINTMENT_SUCCESS',
        REQUEST_QUOTE_SUCCESS:        'REQUEST_QUOTE_SUCCESS',
        EMAIL_QUOTE_SUCCESS:          'EMAIL_QUOTE_SUCCESS',
        PRINT_QUOTE_SUCCESS:          'PRINT_QUOTE_SUCCESS',

        SEND_APPOINTMENT_ERROR:     'SEND_APPOINTMENT_ERROR',
        REQUEST_QUOTE_ERROR:        'REQUEST_QUOTE_ERROR',
        EMAIL_QUOTE_ERROR:          'EMAIL_QUOTE_ERROR',
        PRINT_QUOTE_ERROR:          'PRINT_QUOTE_ERROR',

        ORDER_CREATE_SUCCESS:       'ORDER_CREATE_SUCCESS',
        ORDER_PAYMENT_SUCCESS:      'ORDER_PAYMENT_SUCCESS',
        ORDER_CHECKOUT_SUCCESS:     'ORDER_CHECKOUT_SUCCESS',
        ORDER_CREATE_ERROR:         'ORDER_CREATE_ERROR',
        ORDER_PAYMENT_ERROR:        'ORDER_PAYMENT_ERROR',
        ORDER_CHECKOUT_ERROR:       'ORDER_CHECKOUT_ERROR',

        LOAD_FULL_STOCK_SUCCESS:     'LOAD_FULL_STOCK_SUCCESS',
        LOAD_STOCK_SUCCESS:          'LOAD_STOCK_SUCCESS',

        LOAD_REVIEWS_SUCCESS:   'LOAD_REVIEWS_SUCCESS',

        // ----- User actions events -----
        CHANGE_LOCATION:             'CHANGE_LOCATION',
        CHANGE_SEARCH_TIRE_PARAM:    'CHANGE_SEARCH_TIRE_PARAM',
        CHANGE_SEARCH_VEHICLE_PARAM: 'CHANGE_SEARCH_VEHICLE_PARAM',
        CHANGE_SEARCH_BY:            'CHANGE_SEARCH_BY',

        SEARCH_TIRES:                'SEARCH_TIRES',
                
        SELECT_TIRE:     'SELECT_TIRE',
        UPDATE_QUOTE:    'UPDATE_QUOTE',

        SHOW_QUOTE_REQUEST_FORM: 'SHOW_QUOTE_REQUEST_FORM',
        SHOW_APPOINTMENT_FORM:   'SHOW_APPOINTMENT_FORM',
        SHOW_QUOTE_PAGE:         'SHOW_QUOTE_PAGE',
        SHOW_QUOTE_EMAIL_FORM:   'SHOW_QUOTE_EMAIL_FORM',
        SHOW_QUOTE_PRINT_FORM:   'SHOW_QUOTE_PRINT_FORM',

        ORDER_CREATE:            'ORDER_CREATE',
        ORDER_PAYMENT:           'ORDER_PAYMENT',

        SEND_APPOINTMENT:   'SEND_APPOINTMENT',
        SEND_QUOTE_REQUEST: 'SEND_QUOTE_REQUEST',
        SEND_EMAIL:         'SEND_EMAIL',
        PRINT_QUOTE:        'PRINT_QUOTE'
    };
});